//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grupo6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedidos
    {
        public int Id_Pedido { get; set; }
        public int Id_Producto { get; set; }
        public int Id_Persona { get; set; }
        public int Id_Entrega { get; set; }
        public decimal Precio { get; set; }
        public int Id_estado_pedido { get; set; }
    
        public virtual Persona Persona { get; set; }
        public virtual Producto Producto { get; set; }
        public virtual Ventas Ventas { get; set; }
    }
}
