//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grupo6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto()
        {
            this.Pedidos = new HashSet<Pedidos>();
        }
    
        public int Id_Producto { get; set; }
        public string Nombre_Producto { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<int> Id_Estado { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<int> Id_Ubicacion { get; set; }
    
        public virtual Estado_Productos Estado_Productos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pedidos> Pedidos { get; set; }
        public virtual Ubicacion Ubicacion { get; set; }
    }
}
