//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grupo6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ventas
    {
        public int Id_pedido { get; set; }
        public Nullable<int> Id_persona { get; set; }
        public Nullable<int> Id_entrega { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public Nullable<decimal> Precio_Total { get; set; }
        public Nullable<int> Id_estado_pedido { get; set; }
    
        public virtual Estado_Pedido Estado_Pedido { get; set; }
        public virtual Pedidos Pedidos { get; set; }
        public virtual Persona Persona { get; set; }
        public virtual Tipo_Entrega Tipo_Entrega { get; set; }
    }
}
